### ISSUE TITLE
Questions about camera parameters and scene parameter in dataset

### ISSUE THREAD

**Issue by dogyoonlee** [google/hypernerf#4]
Hello, I really appreciate to this awesome work!!

To experiment on your dataset with pytorch framework, 
First, I''m trying to reimplemen nerfies data loader(HyperNeRF data loader) in pytorch.

However, I have some questions about camera parameters and scene parameters in dataset.

1. What does the `scale`, `scene_to_metric` and `bbox` in `scene.json` file??
What is differences between above `scale` parameter and **'scale'** of images like `4x`? ( _scale of image_ vs _scale of scene_ )

[ scene_scale is applied ]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/62277785/142561853-0f1e943c-1927-4445-94b7-9500022c2bdb.png">

2. For `llff data format`, we generate rays using this code. 

[llff data format - get ray function]
![image](https://user-images.githubusercontent.com/62277785/142562023-d5d513d1-eb92-4739-9785-f037f1a313fd.png)

I think that is the simple version of yours(ignore the distortion and assume that principal points is almost same to the center of image)

[ yours ]
![image](https://user-images.githubusercontent.com/62277785/142562283-98710876-6071-4d5e-8ab9-6e53874e3dfd.png)

But you undistorted to generate `dirs` using `principal points`, `tangential distortion`, `radial_distortion`, and `pixel_aspect_ratio`. 
Is there huge difference?

3. Are **HyperNerf** and **Nerfies**  is implemented in NDC(Normalized Device Coordinate)?
Usually many Nerf-based models have been implemented in NDC.

It will be really helpful for me if you answer this question!!
Thanks for your awesome work again!

Best regards
Dogyoon Lee

**Comment by keunhong** [comment]
Hi Dogyoon. Thanks for your efforts!

### What does the scale, scene_to_metric and bbox in scene.json file??
You can safely ignore `scene_to_metric` and `bbox`, they're not used. `scale` is the scale factor that converts the COLMAP coordinate to something smaller that can fit in a reasonable range. It's used here https://github.com/google/hypernerf/blob/59ca296c6cf4369f81177b928656aea62d085fd2/hypernerf/datasets/nerfies.py#L53 and it's computed in the dataset processing notebooks using some heuristics.

### Undistortion in LLFF vs here.
The difference is that some other NeRF papers pre-undistort the image and then use a pinhole camera, whereas we use the tangential and radial distortion parameters to generate the rays. The disadvantage of pre-undistorting is that you have to discard the border pixels since it can leave some invalid pixels. We also get to use the image pixels directly which can be nicer.

### NDC
We don't use NDC, since some of our captures aren't fully front-facing and we don't really care about reconstructing far away backgrounds.

**Comment by tommaoer** [comment]
@keunhong hi, thanks for your awesome work! I have encountered a problem when I want to preprocess data. 
I notice that the 'scale' in 'scene.json' of all your release [data](https://github.com/google/hypernerf/releases/tag/v0.1) are the 0.04. But, I have preprocessed the original image sequences from 'rgb/1x' folder of each example, but the 'scale' of scene has a huge difference between the released data. And if I use my preprocessed data to train the nerf,  it will get a bad result. I want to know the reason. 
Thanks
